# DQNエージェント NN構造定義ファイル(全結合型NN)
# ファイル名は変更しないこと!

### 第i層(i番目の中間層)の情報 ###
# layer_i: [ユニット数(int), バイアスの有無(bool), 活性化関数(str)]
# 利用できる関数名は以下の通り。
# relu: ReLU
# sigmoid: Sigmoid

layer_1: [100, true, relu]
layer_2: [100, true, relu]
layer_3: [100, true, relu]

### 注意 ###
# i)    入出力層については記述不要。環境の仕様に応じて自動で作成される。
# ii)   第i層の出力は、第i+1層のみに入力されるものとする。層を飛び越えた結合は未対応。
# iii)  中間層では、全結合層と活性化関数が繰り返される。
# iv)   Pytorchを利用する場合、層はその仕様の都合上設定よりも1層多く作成される。
#       その際、最後の層については活性化関数なし、バイアスの有無は設定で定義した最後の
#       中間層と同じとなる。
