# DQNエージェント NN構造定義ファイル(CNN)
# ファイル名は変更しないこと!

### i番目の畳み込み層の情報 ###
# conv_i: [
#   出力チャンネル数(int),
#   カーネルサイズ(WH) (int, int),
#   パディング(XY) (int, int),
#   ストライド(XY) (int, int),
#   バイアスの有無 (bool),
#   活性化関数(str)
#]
#
# 利用できる活性化関数名は以下の通り。
# relu: ReLU
# sigmoid: Sigmoid

conv_1: [4, [3, 3], [0, 0], [1, 1], true, relu]

### i番目の全結合層の情報 ###
# fc_i: [ユニット数(int), バイアスの有無(bool), 活性化関数(str)]
# 利用できる関数名は以下の通り。
# relu: ReLU
# sigmoid: Sigmoid

fc_1: [30, true, relu]

### 注意 ###
# i)    第i層の出力は、第i+1層のみに入力されるものとする。層を飛び越えた結合は未対応。
# ii)   畳み込み層では、畳み込み層 -> 活性化関数が繰り返される。
# iii)  dilated convolutionについては考慮しない。
# iv)   Pytorchを利用する場合、その仕様の都合上全結合層は設定よりも1層多く作成される。
#       その際、最後の層については活性化関数なし、バイアスの有無は設定で定義した最後の
#       全結合層と同じとなる。
# TODO: プーリングもできるようにする。
